import { describe, expect, it, jest } from '@jest/globals';
import { decryptSecret, encryptSecret, generateTotpSecret, totp, verifyTotp } from '@complyos/runtime/mfa';
import { enforceRecordScope, projectAuditorRecord, projectVendorRecord, requirePermission, tenantRepository, TenantAccessDenied } from '@complyos/runtime/authorization';
import { enforcePasswordPolicy, fixtureBreachChecker, SecurityPolicyError } from '@complyos/runtime/security';
import { organizationStore } from '@complyos/runtime/organizations';
describe('MFA and tenant policy helpers', () => {
  it('encrypts TOTP secrets and validates only the current time window', () => { const secret = generateTotpSecret(); const encrypted = encryptSecret(secret, 'master-secret-at-least-32-characters'); expect(encrypted).not.toContain(secret); expect(decryptSecret(encrypted, 'master-secret-at-least-32-characters')).toBe(secret); expect(verifyTotp(secret, totp(secret))).toBe(true); expect(verifyTotp(secret, '000000', 0)).toBe(false); });
  it('enforces permission, tenant, owner and department scope', () => { const context = { userId: 'u', sessionId: 's', organizationId: 'tenant-a', membershipId: 'member-a', permissions: ['records:read'] }; expect(() => requirePermission(context, 'records:write')).toThrow(TenantAccessDenied); expect(() => enforceRecordScope(context, { organizationId: 'tenant-b', ownerMembershipId: 'member-a' })).toThrow(TenantAccessDenied); expect(() => enforceRecordScope(context, { organizationId: 'tenant-a', ownerMembershipId: 'member-b' }, { ownerOnly: true })).toThrow(TenantAccessDenied); expect(() => enforceRecordScope(context, { organizationId: 'tenant-a', departmentId: 'd2' }, { departmentIds: ['d1'] })).toThrow(TenantAccessDenied); });
  it('projects away internal fields for vendors and auditors', () => { const record = { id: 'r', name: 'Control', internalNotes: 'secret', vendorVisibleSummary: 'shared' }; expect(projectVendorRecord(record)).toEqual({ id: 'r', name: 'Control', summary: 'shared' }); expect(projectAuditorRecord(record)).not.toHaveProperty('internalNotes'); });
  it('always tenant-filters fetches and mutations, preventing ID substitution', async () => { const query = jest.fn().mockResolvedValue({ rows: [] }); const context = { userId: 'u', sessionId: 's', organizationId: 'tenant-a', membershipId: 'm', permissions: [] }; const repo = tenantRepository({ query }, context); await repo.findSample('tenant-b-record'); await repo.renameSample('tenant-b-record', 'changed'); expect(query.mock.calls[0][1]).toEqual(['tenant-b-record', 'tenant-a']); expect(query.mock.calls[1][1]).toEqual(['tenant-b-record', 'tenant-a', 'changed']); });
  it('rejects compromised fixture passwords and documents fail-open provider outages', async () => { const db = { query: jest.fn().mockResolvedValue({ rows: [{}] }) }; await expect(enforcePasswordPolicy(db, 'letmein123456')).rejects.toBeInstanceOf(SecurityPolicyError); await expect(enforcePasswordPolicy(db, 'safe lengthy passphrase', [], { check: async () => 'unavailable' })).resolves.toBeUndefined(); expect(await fixtureBreachChecker().check('password123')).toBe('compromised'); });
  it('rejects organization listing without a verified active tenant context', async()=>{const db={query:jest.fn().mockResolvedValue({rows:[],rowCount:0})};await expect(organizationStore(db).list('user','session',{page:1,limit:20})).rejects.toBeInstanceOf(TenantAccessDenied);});
});
