import{useState}from'react';
import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{Button}from'@/components/ui/button';
import{useAuth}from'@/lib/auth';

type Mapping={id:string;frameworkName:string;versionIdentifier:string;requirementReference:string;coverage:number;mappingType:string;rationale:string;approvalStatus:string;provenance:Record<string,unknown>;reviewComment?:string|null};
type Review={mappings:Mapping[]};

export function MappingReviewList({implementationId}:{implementationId:string}){
 const{authenticatedFetch}=useAuth(),client=useQueryClient(),[comments,setComments]=useState<Record<string,string>>({}),[message,setMessage]=useState('');
 const review=useQuery({queryKey:['mapping-review',implementationId],queryFn:()=>authenticatedFetch<Review>(`/api/v1/control-implementations/${implementationId}/review`)});
 const decision=useMutation({mutationFn:({id,value,comment}:{id:string;value:'APPROVED'|'REJECTED';comment:string})=>authenticatedFetch(`/api/v1/control-mappings/${id}/decision`,{method:'POST',body:JSON.stringify({decision:value,comment})}),onSuccess:async()=>{setMessage('Mapping decision recorded.');await client.invalidateQueries({queryKey:['mapping-review',implementationId]})},onError:()=>setMessage('The mapping decision could not be recorded. Retry.')});
 const mappings=Array.isArray(review.data?.mappings)?review.data.mappings:[];
 return <section className="border-t py-8"><h2 className="text-xl font-semibold">Mapping review</h2><p className="mt-1 text-sm text-muted-foreground">Review each edition-pinned requirement mapping and record a comment with the decision.</p>{review.isLoading&&<div className="mt-5 h-24 animate-pulse rounded-lg bg-muted"/>}{review.isError&&<p role="alert" className="mt-4 text-sm text-destructive">Mappings could not be loaded.</p>}{!review.isLoading&&!mappings.length&&<p className="mt-4 text-sm text-muted-foreground">No mappings are ready for review.</p>}<div className="mt-5 space-y-4">{mappings.map(mapping=>{const comment=comments[mapping.id]??'';return <article key={mapping.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{mapping.frameworkName} · {mapping.versionIdentifier} · {mapping.requirementReference}</h3><p className="mt-1 text-sm text-muted-foreground">{mapping.mappingType} · {mapping.coverage}% coverage · {mapping.approvalStatus}</p></div></div><p className="mt-3 text-sm">{mapping.rationale}</p><p className="mt-2 break-all text-xs text-muted-foreground">Source: {String(mapping.provenance?.source??'unspecified')}</p>{mapping.reviewComment&&<p className="mt-3 text-sm"><span className="font-medium">Latest review:</span> {mapping.reviewComment}</p>}<label htmlFor={`mapping-comment-${mapping.id}`} className="mt-4 block text-sm font-medium">Reviewer comment<textarea id={`mapping-comment-${mapping.id}`} className="field mt-2 min-h-20 py-3" value={comment} onChange={event=>setComments(current=>({...current,[mapping.id]:event.target.value}))}/></label><div className="mt-3 flex gap-2"><Button disabled={!comment.trim()||decision.isPending} onClick={()=>decision.mutate({id:mapping.id,value:'APPROVED',comment})}>{decision.isPending?'Recording…':'Approve'}</Button><Button variant="outline" disabled={!comment.trim()||decision.isPending} onClick={()=>decision.mutate({id:mapping.id,value:'REJECTED',comment})}>{decision.isPending?'Recording…':'Reject'}</Button></div></article>})}</div>{decision.isPending&&<p role="status" className="mt-4 text-sm text-muted-foreground">Recording mapping decision…</p>}{message&&!decision.isPending&&<p role={decision.isError?'alert':'status'} className={`mt-4 text-sm ${decision.isError?'text-destructive':'text-primary'}`}>{message}</p>}</section>
}
