import { randomUUID } from 'node:crypto';
import type { Database } from './database.js';
import { resolveTenantContext, TenantAccessDenied } from './authorization.js';
import { appendAudit, ConcurrencyConflict } from './governance.js';

export type BusinessUnitType='DIVISION'|'SUBSIDIARY'|'FUNCTION'|'OTHER';
export interface BusinessUnitInput{name:string;type:BusinessUnitType;parentUnitId?:string|null}

export function businessUnitStore(db:Database){
 const projection='b."id",b."organizationId",b."name",b."type",b."parentUnitId",p."name" AS "parentName",b."version",b."createdAt",b."updatedAt"';
 const context=(userId:string,sessionId:string)=>resolveTenantContext(db,userId,sessionId);
 const parentExists=async(query:Database['query'],organizationId:string,parentUnitId:string|null|undefined)=>{if(!parentUnitId)return;const result=await query('SELECT 1 FROM "BusinessUnit" WHERE "id"=$1 AND "organizationId"=$2',[parentUnitId,organizationId]);if(!result.rowCount)throw new TenantAccessDenied();};
 return{
  async list(userId:string,sessionId:string,input:{page:number;limit:number}){const actor=await context(userId,sessionId);const offset=(input.page-1)*input.limit;const result=await db.query(`SELECT ${projection},COUNT(*) OVER()::int AS "totalCount" FROM "BusinessUnit" b LEFT JOIN "BusinessUnit" p ON p."id"=b."parentUnitId" AND p."organizationId"=b."organizationId" WHERE b."organizationId"=$1 ORDER BY b."name",b."id" LIMIT $2 OFFSET $3`,[actor.organizationId,input.limit,offset]);return{data:result.rows.map(({totalCount:_,...row})=>row),total:result.rows[0]?.totalCount??0,page:input.page,limit:input.limit};},
  async create(userId:string,sessionId:string,input:BusinessUnitInput,requestId:string){const actor=await context(userId,sessionId);if(!actor.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');await parentExists(client.query.bind(client),actor.organizationId,input.parentUnitId);const id=randomUUID();await client.query('INSERT INTO "BusinessUnit" ("id","organizationId","name","type","parentUnitId") VALUES ($1,$2,$3,$4,$5)',[id,actor.organizationId,input.name,input.type,input.parentUnitId??null]);const created=await client.query(`SELECT ${projection} FROM "BusinessUnit" b LEFT JOIN "BusinessUnit" p ON p."id"=b."parentUnitId" AND p."organizationId"=b."organizationId" WHERE b."id"=$1 AND b."organizationId"=$2`,[id,actor.organizationId]);await appendAudit(client.query.bind(client),{organizationId:actor.organizationId,actorUserId:userId,actorMembershipId:actor.membershipId,action:'business-unit.created',resourceType:'BusinessUnit',resourceId:id,after:created.rows[0],requestId});await client.query('COMMIT');return created.rows[0];}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}},
  async detail(userId:string,sessionId:string,id:string){const actor=await context(userId,sessionId);const result=await db.query(`SELECT ${projection} FROM "BusinessUnit" b LEFT JOIN "BusinessUnit" p ON p."id"=b."parentUnitId" AND p."organizationId"=b."organizationId" WHERE b."id"=$1 AND b."organizationId"=$2`,[id,actor.organizationId]);return result.rows[0]??null;},
  async update(userId:string,sessionId:string,id:string,input:Partial<BusinessUnitInput>&{version:number},requestId:string){const actor=await context(userId,sessionId);if(!actor.permissions.includes('organization:manage'))throw new TenantAccessDenied();if(input.parentUnitId===id)throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');await parentExists(client.query.bind(client),actor.organizationId,input.parentUnitId);const prior=await client.query('SELECT * FROM "BusinessUnit" WHERE "id"=$1 AND "organizationId"=$2 FOR UPDATE',[id,actor.organizationId]);if(!prior.rowCount)throw new TenantAccessDenied();const result=await client.query('UPDATE "BusinessUnit" SET "name"=COALESCE($4,"name"),"type"=COALESCE($5,"type"),"parentUnitId"=CASE WHEN $6::boolean THEN $7::uuid ELSE "parentUnitId" END,"version"="version"+1,"updatedAt"=NOW() WHERE "id"=$1 AND "organizationId"=$2 AND "version"=$3 RETURNING *',[id,actor.organizationId,input.version,input.name??null,input.type??null,Object.prototype.hasOwnProperty.call(input,'parentUnitId'),input.parentUnitId??null]);if(!result.rowCount)throw new ConcurrencyConflict('Business unit changed after it was loaded.');await appendAudit(client.query.bind(client),{organizationId:actor.organizationId,actorUserId:userId,actorMembershipId:actor.membershipId,action:'business-unit.updated',resourceType:'BusinessUnit',resourceId:id,before:prior.rows[0],after:result.rows[0],requestId});const updated=await client.query(`SELECT ${projection} FROM "BusinessUnit" b LEFT JOIN "BusinessUnit" p ON p."id"=b."parentUnitId" AND p."organizationId"=b."organizationId" WHERE b."id"=$1 AND b."organizationId"=$2`,[id,actor.organizationId]);await client.query('COMMIT');return updated.rows[0];}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}},
 };
}
