import { randomUUID } from 'node:crypto';
import type { Database } from './database.js';
import { resolveTenantContext, TenantAccessDenied } from './authorization.js';
import { appendAudit, ConcurrencyConflict } from './governance.js';

export type ControlType='PREVENTIVE'|'DETECTIVE'|'CORRECTIVE'|'DIRECTIVE';
export type ControlFrequency='CONTINUOUS'|'DAILY'|'WEEKLY'|'MONTHLY'|'QUARTERLY'|'ANNUALLY'|'EVENT_DRIVEN';
export interface ControlInput { reference:string; title:string; objective:string; type:ControlType; category:string; guidance?:string; testProcedure?:string; frequency:ControlFrequency }

export function controlStore(db:Database){
 const projection='c."id",c."organizationId",c."reference",c."title",c."objective",c."type",c."category",c."guidance",c."testProcedure",c."frequency",c."version",c."createdAt",c."updatedAt",(SELECT i."id" FROM "ControlImplementation" i WHERE i."controlId"=c."id" AND i."organizationId"=c."organizationId" ORDER BY i."id" LIMIT 1) AS "implementationId"';
 const context=(u:string,s:string)=>resolveTenantContext(db,u,s);
 return {
  async list(userId:string,sessionId:string,input:{page:number;limit:number}){const a=await context(userId,sessionId);const r=await db.query(`SELECT ${projection},COUNT(*) OVER()::int AS "totalCount" FROM "UnifiedControl" c WHERE c."organizationId"=$1 OR c."organizationId" IS NULL ORDER BY c."reference",c."id" LIMIT $2 OFFSET $3`,[a.organizationId,input.limit,(input.page-1)*input.limit]);return {data:r.rows.map(({totalCount:_,...x})=>x),total:r.rows[0]?.totalCount??0,page:input.page,limit:input.limit};},
  async detail(userId:string,sessionId:string,id:string){const a=await context(userId,sessionId);const r=await db.query(`SELECT ${projection} FROM "UnifiedControl" c WHERE c."id"=$1 AND (c."organizationId"=$2 OR c."organizationId" IS NULL)`,[id,a.organizationId]);return r.rows[0]??null;},
  async create(userId:string,sessionId:string,input:ControlInput,requestId:string){const a=await context(userId,sessionId);if(!a.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');const id=randomUUID(),implementationId=randomUUID();const r=await client.query('INSERT INTO "UnifiedControl" ("id","organizationId","reference","title","objective","type","category","guidance","testProcedure","frequency") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id,a.organizationId,input.reference,input.title,input.objective,input.type,input.category,input.guidance??null,input.testProcedure??null,input.frequency]);await client.query('INSERT INTO "ControlImplementation"("id","organizationId","controlId","implementationScope","status") VALUES($1,$2,$3,$4,\'PLANNED\')',[implementationId,a.organizationId,id,{}]);await appendAudit(client.query.bind(client),{organizationId:a.organizationId,actorUserId:userId,actorMembershipId:a.membershipId,action:'control.created',resourceType:'UnifiedControl',resourceId:id,after:r.rows[0],requestId});await client.query('COMMIT');return{...r.rows[0],implementationId};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}},
  async update(userId:string,sessionId:string,id:string,input:Partial<ControlInput>&{version:number},requestId:string){const a=await context(userId,sessionId);if(!a.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');const before=await client.query('SELECT * FROM "UnifiedControl" WHERE "id"=$1 AND "organizationId"=$2 FOR UPDATE',[id,a.organizationId]);if(!before.rowCount)throw new TenantAccessDenied();const r=await client.query('UPDATE "UnifiedControl" SET "reference"=COALESCE($4,"reference"),"title"=COALESCE($5,"title"),"objective"=COALESCE($6,"objective"),"type"=COALESCE($7,"type"),"category"=COALESCE($8,"category"),"guidance"=COALESCE($9,"guidance"),"testProcedure"=COALESCE($10,"testProcedure"),"frequency"=COALESCE($11,"frequency"),"version"="version"+1,"updatedAt"=NOW() WHERE "id"=$1 AND "organizationId"=$2 AND "version"=$3 RETURNING *',[id,a.organizationId,input.version,input.reference??null,input.title??null,input.objective??null,input.type??null,input.category??null,input.guidance??null,input.testProcedure??null,input.frequency??null]);if(!r.rowCount)throw new ConcurrencyConflict('Control changed after it was loaded.');await appendAudit(client.query.bind(client),{organizationId:a.organizationId,actorUserId:userId,actorMembershipId:a.membershipId,action:'control.updated',resourceType:'UnifiedControl',resourceId:id,before:before.rows[0],after:r.rows[0],requestId});await client.query('COMMIT');return r.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
 };
}
