import { randomUUID } from 'node:crypto';
import type { Database } from './database.js';
import { resolveTenantContext,TenantAccessDenied } from './authorization.js';
import { appendAudit,ConcurrencyConflict } from './governance.js';
export interface DepartmentInput{name:string;businessUnitId?:string|null;headMembershipId?:string|null}
export function departmentStore(db:Database){
 const projection='d."id",d."organizationId",d."name",d."businessUnitId",b."name" AS "businessUnitName",d."headMembershipId",u."displayName" AS "headName",d."version",d."createdAt",d."updatedAt"';
 const joins='FROM "Department" d LEFT JOIN "BusinessUnit" b ON b."id"=d."businessUnitId" AND b."organizationId"=d."organizationId" LEFT JOIN "OrganizationMembership" m ON m."id"=d."headMembershipId" AND m."organizationId"=d."organizationId" LEFT JOIN "User" u ON u."id"=m."userId"';
 const context=(u:string,s:string)=>resolveTenantContext(db,u,s);
 const validateLinks=async(query:Database['query'],org:string,input:Partial<DepartmentInput>)=>{if(input.businessUnitId){const r=await query('SELECT 1 FROM "BusinessUnit" WHERE "id"=$1 AND "organizationId"=$2',[input.businessUnitId,org]);if(!r.rowCount)throw new TenantAccessDenied();}if(input.headMembershipId){const r=await query('SELECT 1 FROM "OrganizationMembership" WHERE "id"=$1 AND "organizationId"=$2 AND "status"=\'ACTIVE\'',[input.headMembershipId,org]);if(!r.rowCount)throw new TenantAccessDenied();}};
 return{
  async options(userId:string,sessionId:string){const actor=await context(userId,sessionId);const result=await db.query('SELECT m."id",u."displayName",u."email" FROM "OrganizationMembership" m JOIN "User" u ON u."id"=m."userId" WHERE m."organizationId"=$1 AND m."status"=\'ACTIVE\' ORDER BY u."displayName",u."email"',[actor.organizationId]);return result.rows;},
  async list(userId:string,sessionId:string,input:{page:number;limit:number}){const actor=await context(userId,sessionId);const result=await db.query(`SELECT ${projection},COUNT(*) OVER()::int AS "totalCount" ${joins} WHERE d."organizationId"=$1 ORDER BY d."name",d."id" LIMIT $2 OFFSET $3`,[actor.organizationId,input.limit,(input.page-1)*input.limit]);return{data:result.rows.map(({totalCount:_,...row})=>row),total:result.rows[0]?.totalCount??0,page:input.page,limit:input.limit};},
  async create(userId:string,sessionId:string,input:DepartmentInput,requestId:string){const actor=await context(userId,sessionId);if(!actor.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');await validateLinks(client.query.bind(client),actor.organizationId,input);const id=randomUUID();await client.query('INSERT INTO "Department" ("id","organizationId","name","businessUnitId","headMembershipId") VALUES ($1,$2,$3,$4,$5)',[id,actor.organizationId,input.name,input.businessUnitId??null,input.headMembershipId??null]);const created=await client.query(`SELECT ${projection} ${joins} WHERE d."id"=$1 AND d."organizationId"=$2`,[id,actor.organizationId]);await appendAudit(client.query.bind(client),{organizationId:actor.organizationId,actorUserId:userId,actorMembershipId:actor.membershipId,action:'department.created',resourceType:'Department',resourceId:id,after:created.rows[0],requestId});await client.query('COMMIT');return created.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}},
  async detail(userId:string,sessionId:string,id:string){const actor=await context(userId,sessionId);const r=await db.query(`SELECT ${projection} ${joins} WHERE d."id"=$1 AND d."organizationId"=$2`,[id,actor.organizationId]);return r.rows[0]??null;},
  async update(userId:string,sessionId:string,id:string,input:Partial<DepartmentInput>&{version:number},requestId:string){const actor=await context(userId,sessionId);if(!actor.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');await validateLinks(client.query.bind(client),actor.organizationId,input);const prior=await client.query('SELECT * FROM "Department" WHERE "id"=$1 AND "organizationId"=$2 FOR UPDATE',[id,actor.organizationId]);if(!prior.rowCount)throw new TenantAccessDenied();const r=await client.query('UPDATE "Department" SET "name"=COALESCE($4,"name"),"businessUnitId"=CASE WHEN $5::boolean THEN $6::uuid ELSE "businessUnitId" END,"headMembershipId"=CASE WHEN $7::boolean THEN $8::uuid ELSE "headMembershipId" END,"version"="version"+1,"updatedAt"=NOW() WHERE "id"=$1 AND "organizationId"=$2 AND "version"=$3 RETURNING *',[id,actor.organizationId,input.version,input.name??null,Object.hasOwn(input,'businessUnitId'),input.businessUnitId??null,Object.hasOwn(input,'headMembershipId'),input.headMembershipId??null]);if(!r.rowCount)throw new ConcurrencyConflict('Department changed after it was loaded.');await appendAudit(client.query.bind(client),{organizationId:actor.organizationId,actorUserId:userId,actorMembershipId:actor.membershipId,action:'department.updated',resourceType:'Department',resourceId:id,before:prior.rows[0],after:r.rows[0],requestId});const updated=await client.query(`SELECT ${projection} ${joins} WHERE d."id"=$1 AND d."organizationId"=$2`,[id,actor.organizationId]);await client.query('COMMIT');return updated.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
 };
}
