import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function base32Encode(input: Buffer) { let bits = ''; for (const byte of input) bits += byte.toString(2).padStart(8, '0'); let output = ''; for (let i = 0; i < bits.length; i += 5) output += alphabet[parseInt(bits.slice(i, i + 5).padEnd(5, '0'), 2)]; return output; }
function base32Decode(input: string) { let bits = ''; for (const char of input.replace(/=+$/, '').toUpperCase()) { const index = alphabet.indexOf(char); if (index < 0) throw new Error('Invalid base32'); bits += index.toString(2).padStart(5, '0'); } const bytes: number[] = []; for (let i = 0; i + 8 <= bits.length; i += 8) bytes.push(parseInt(bits.slice(i, i + 8), 2)); return Buffer.from(bytes); }
export function generateTotpSecret() { return base32Encode(randomBytes(20)); }
export function totp(secret: string, time = Date.now()) { const counter = Math.floor(time / 30000); const buffer = Buffer.alloc(8); buffer.writeBigUInt64BE(BigInt(counter)); const digest = createHmac('sha1', base32Decode(secret)).update(buffer).digest(); const offset = digest[19] & 15; const value = (digest.readUInt32BE(offset) & 0x7fffffff) % 1_000_000; return value.toString().padStart(6, '0'); }
export function verifyTotp(secret: string, code: string, time = Date.now()) { return [-1, 0, 1].some(step => { const candidateTime = time + step * 30000; if (candidateTime < 0) return false; const expected = Buffer.from(totp(secret, candidateTime)); const actual = Buffer.from(code); return expected.length === actual.length && timingSafeEqual(expected, actual); }); }
const key = (secret: string) => createHmac('sha256', secret).update('complyos-mfa-encryption-v1').digest();
export function encryptSecret(secret: string, master: string) { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key(master), iv); const encrypted = Buffer.concat([cipher.update(secret, 'utf8'), cipher.final()]); return [iv, cipher.getAuthTag(), encrypted].map(value => value.toString('base64url')).join('.'); }
export function decryptSecret(value: string, master: string) { const [iv, tag, encrypted] = value.split('.').map(part => Buffer.from(part, 'base64url')); const decipher = createDecipheriv('aes-256-gcm', key(master), iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString('utf8'); }
