import { randomUUID } from 'node:crypto';
import type { Database } from './database.js';
import { resolveTenantContext, TenantAccessDenied } from './authorization.js';
import { appendAudit, ConcurrencyConflict } from './governance.js';
import { BUILT_IN_ROLES, PERMISSIONS, ROLE_PERMISSION_MATRIX } from './roles.js';

export interface OrganizationInput { name:string; industry?:string; registrationNumber?:string; country?:string; timezone:string; employeeCount?:number; website?:string; contacts?:Array<{name:string;email?:string;phone?:string}> }
export function organizationStore(db:Database){
 const context=(userId:string,sessionId:string)=>resolveTenantContext(db,userId,sessionId);
 const projection='o."id",o."name",o."industry",o."registrationNumber",o."country",o."timezone",o."employeeCount",o."website",o."contacts",o."version",o."createdAt",o."updatedAt"';
 return {
  async list(userId:string,sessionId:string,input:{page:number;limit:number}){await context(userId,sessionId);const offset=(input.page-1)*input.limit;const result=await db.query(`SELECT ${projection},COUNT(*) OVER()::int AS "totalCount" FROM "Organization" o JOIN "OrganizationMembership" m ON m."organizationId"=o."id" AND m."userId"=$1 AND m."status"='ACTIVE' WHERE o."disabledAt" IS NULL ORDER BY o."name",o."id" LIMIT $2 OFFSET $3`,[userId,input.limit,offset]);return{data:result.rows.map(({totalCount:_,...row})=>row),total:result.rows[0]?.totalCount??0,page:input.page,limit:input.limit};},
  async create(userId:string,sessionId:string,input:OrganizationInput,requestId:string){const actor=await context(userId,sessionId);if(!actor.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');const organizationId=randomUUID();const membershipId=randomUUID();await client.query(`INSERT INTO "Organization" ("id","name","industry","registrationNumber","country","timezone","employeeCount","website","contacts") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[organizationId,input.name,input.industry??null,input.registrationNumber??null,input.country??null,input.timezone,input.employeeCount??null,input.website??null,input.contacts??[]]);await client.query(`INSERT INTO "OrganizationMembership" ("id","organizationId","userId","status") VALUES ($1,$2,$3,'ACTIVE')`,[membershipId,organizationId,userId]);const permissionIds=new Map<string,string>();for(const key of PERMISSIONS){const id=randomUUID();const result=await client.query(`INSERT INTO "Permission" ("id","key") VALUES ($1,$2) ON CONFLICT("key") DO UPDATE SET "key"=EXCLUDED."key" RETURNING "id"`,[id,key]);permissionIds.set(key,result.rows[0].id);}for(const name of BUILT_IN_ROLES){const roleId=randomUUID();await client.query(`INSERT INTO "Role" ("id","organizationId","name","isSystem") VALUES ($1,$2,$3,TRUE)`,[roleId,organizationId,name]);for(const key of ROLE_PERMISSION_MATRIX[name])await client.query(`INSERT INTO "RolePermission" ("roleId","permissionId") VALUES ($1,$2)`,[roleId,permissionIds.get(key)]);if(name==='Organization Owner')await client.query(`INSERT INTO "MembershipRole" ("membershipId","roleId","organizationId") VALUES ($1,$2,$3)`,[membershipId,roleId,organizationId]);}await appendAudit(client.query.bind(client),{organizationId,actorUserId:userId,actorMembershipId:membershipId,action:'organization.created',resourceType:'Organization',resourceId:organizationId,after:input,requestId});const created=await client.query(`SELECT ${projection} FROM "Organization" o WHERE o."id"=$1`,[organizationId]);await client.query('COMMIT');return created.rows[0];}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}},
  async detail(userId:string,sessionId:string,id:string){await context(userId,sessionId);const result=await db.query(`SELECT ${projection} FROM "Organization" o JOIN "OrganizationMembership" m ON m."organizationId"=o."id" AND m."userId"=$2 AND m."status"='ACTIVE' WHERE o."id"=$1 AND o."disabledAt" IS NULL`,[id,userId]);return result.rows[0]??null;},
  async update(userId:string,sessionId:string,id:string,input:Partial<OrganizationInput>&{version:number},requestId:string){const actor=await context(userId,sessionId);if(actor.organizationId!==id||!actor.permissions.includes('organization:manage'))throw new TenantAccessDenied();const client=await db.connect();try{await client.query('BEGIN');const prior=await client.query(`SELECT ${projection} FROM "Organization" o WHERE o."id"=$1 FOR UPDATE`,[id]);if(!prior.rowCount)throw new TenantAccessDenied();const result=await client.query(`UPDATE "Organization" SET "name"=COALESCE($3,"name"),"industry"=COALESCE($4,"industry"),"registrationNumber"=COALESCE($5,"registrationNumber"),"country"=COALESCE($6,"country"),"timezone"=COALESCE($7,"timezone"),"employeeCount"=COALESCE($8,"employeeCount"),"website"=COALESCE($9,"website"),"contacts"=COALESCE($10,"contacts"),"version"="version"+1,"updatedAt"=NOW() WHERE "id"=$1 AND "version"=$2 RETURNING *`,[id,input.version,input.name??null,input.industry??null,input.registrationNumber??null,input.country??null,input.timezone??null,input.employeeCount??null,input.website??null,input.contacts??null]);if(!result.rowCount)throw new ConcurrencyConflict('Organization changed after it was loaded.');await appendAudit(client.query.bind(client),{organizationId:id,actorUserId:userId,actorMembershipId:actor.membershipId,action:'organization.updated',resourceType:'Organization',resourceId:id,before:prior.rows[0],after:result.rows[0],requestId});await client.query('COMMIT');return result.rows[0];}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}},
 };
}
