import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { Database } from './database.js';
import { transaction } from './database.js';
import { decryptSecret, encryptSecret, generateTotpSecret, verifyTotp } from './mfa.js';
import { TenantAccessDenied } from './authorization.js';
const hash = (value: string) => createHash('sha256').update(value).digest('hex');
export class SecurityPolicyError extends Error {}
export interface BreachChecker { check(password: string): Promise<'safe' | 'compromised' | 'unavailable'> }
export function fixtureBreachChecker(compromised = ['password', 'password123', 'letmein123456']): BreachChecker { const values = new Set(compromised.map(value => value.toLowerCase())); return { async check(password) { return values.has(password.toLowerCase()) ? 'compromised' : 'safe'; } }; }
export async function enforcePasswordPolicy(db: Database, password: string, organizationIds: string[] = [], breach: BreachChecker = fixtureBreachChecker()) {
  const result = organizationIds.length ? await db.query('SELECT MAX("minimumPasswordLength") AS length, bool_or("requireUppercase") AS upper, bool_or("requireLowercase") AS lower, bool_or("requireNumber") AS number, bool_or("requireSymbol") AS symbol FROM "OrganizationSecurityPolicy" WHERE "organizationId" = ANY($1::uuid[])', [organizationIds]) : { rows: [{}] };
  const policy = result.rows[0] ?? {}; const minimum = Number(policy.length ?? 12);
  if (password.length < minimum || (policy.upper && !/[A-Z]/.test(password)) || (policy.lower && !/[a-z]/.test(password)) || (policy.number && !/\d/.test(password)) || (policy.symbol && !/[^A-Za-z0-9]/.test(password))) throw new SecurityPolicyError('Password does not meet the organization policy.');
  const breachResult = await breach.check(password); if (breachResult === 'compromised') throw new SecurityPolicyError('Choose a password that has not appeared in known breaches.');
  // Fail open on provider unavailability: length/complexity still apply and the local audit boundary remains available.
}
const transitions: Record<string, string[]> = { ACTIVE: ['INACTIVE', 'SUSPENDED', 'LOCKED'], INACTIVE: ['ACTIVE'], SUSPENDED: ['ACTIVE'], LOCKED: ['ACTIVE'] };
export function securityStore(db: Database, masterSecret: string) {
  return {
    async transitionUserStatus(actorUserId: string, organizationId: string, targetUserId: string, status: string) {
      const actor = await db.query(`SELECT 1 FROM "OrganizationMembership" m JOIN "MembershipRole" mr ON mr."membershipId"=m."id" JOIN "RolePermission" rp ON rp."roleId"=mr."roleId" JOIN "Permission" p ON p."id"=rp."permissionId" WHERE m."userId"=$1 AND m."organizationId"=$2 AND m."status"='ACTIVE' AND p."key"='users:manage'`, [actorUserId, organizationId]); if (!actor.rowCount) throw new TenantAccessDenied();
      const target = await db.query('SELECT u."status" FROM "User" u JOIN "OrganizationMembership" m ON m."userId"=u."id" WHERE u."id"=$1 AND m."organizationId"=$2', [targetUserId, organizationId]); const current = target.rows[0]?.status; if (!current || !transitions[current]?.includes(status)) throw new SecurityPolicyError('Invalid user status transition.');
      await db.query('UPDATE "User" SET "status"=$2, "updatedAt"=NOW() WHERE "id"=$1', [targetUserId, status]); if (status !== 'ACTIVE') await db.query('UPDATE "RefreshTokenFamily" SET "revokedAt"=COALESCE("revokedAt",NOW()) WHERE "userId"=$1', [targetUserId]); return { status };
    },
    async beginMfaEnrollment(userId: string, email: string) { const secret = generateTotpSecret(); await db.query('INSERT INTO "MfaEnrollment" ("userId","encryptedSecret","status") VALUES ($1,$2,\'PENDING\') ON CONFLICT ("userId") DO UPDATE SET "encryptedSecret"=EXCLUDED."encryptedSecret", "status"=\'PENDING\', "confirmedAt"=NULL, "updatedAt"=NOW()', [userId, encryptSecret(secret, masterSecret)]); return { secret, otpauthUri: `otpauth://totp/ComplyOS:${encodeURIComponent(email)}?secret=${secret}&issuer=ComplyOS` }; },
    async confirmMfaEnrollment(userId: string, code: string) { const row = (await db.query('SELECT "encryptedSecret" FROM "MfaEnrollment" WHERE "userId"=$1 AND "status"=\'PENDING\'', [userId])).rows[0]; if (!row || !verifyTotp(decryptSecret(row.encryptedSecret, masterSecret), code)) throw new SecurityPolicyError('The authentication code is invalid.'); const codes = Array.from({ length: 10 }, () => randomBytes(5).toString('hex').toUpperCase()); await transaction(db, async client => { await client.query('UPDATE "MfaEnrollment" SET "status"=\'ACTIVE\', "confirmedAt"=NOW(), "updatedAt"=NOW() WHERE "userId"=$1', [userId]); await client.query('DELETE FROM "MfaRecoveryCode" WHERE "userId"=$1', [userId]); for (const codeValue of codes) await client.query('INSERT INTO "MfaRecoveryCode" ("id","userId","codeHash") VALUES ($1,$2,$3)', [randomUUID(), userId, hash(codeValue)]); }); return { enabled: true, recoveryCodes: codes.map(value => `${value.slice(0, 5)}-${value.slice(5)}`) }; },
    async requestMfaReset(userId: string, organizationId: string) { const approver = await db.query(`SELECT m."id" FROM "OrganizationMembership" m JOIN "MembershipRole" mr ON mr."membershipId"=m."id" JOIN "Role" r ON r."id"=mr."roleId" WHERE m."organizationId"=$1 AND m."status"='ACTIVE' AND r."name"='Organization Owner' AND m."userId"<>$2 ORDER BY m."createdAt" LIMIT 1`, [organizationId, userId]); if (!approver.rowCount) throw new SecurityPolicyError('No designated approver is available.'); const id = randomUUID(); await db.query('INSERT INTO "MfaResetRequest" ("id","userId","organizationId","approverMembershipId") VALUES ($1,$2,$3,$4)', [id, userId, organizationId, approver.rows[0].id]); return { id, status: 'PENDING' as const }; },
    async approveMfaReset(approverUserId: string, requestId: string) { return transaction(db, async client => { const request = await client.query('SELECT r.* FROM "MfaResetRequest" r JOIN "OrganizationMembership" m ON m."id"=r."approverMembershipId" WHERE r."id"=$1 AND r."status"=\'PENDING\' AND m."userId"=$2 FOR UPDATE OF r', [requestId, approverUserId]); const row = request.rows[0]; if (!row) throw new TenantAccessDenied(); await client.query('DELETE FROM "MfaEnrollment" WHERE "userId"=$1', [row.userId]); await client.query('UPDATE "MfaResetRequest" SET "status"=\'APPROVED\', "resolvedAt"=NOW() WHERE "id"=$1', [requestId]); await client.query('UPDATE "RefreshTokenFamily" SET "revokedAt"=COALESCE("revokedAt",NOW()) WHERE "userId"=$1', [row.userId]); return { approved: true } as const; }); },
  };
}
