import { useEffect,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ApiError } from '@/lib/api';
import { useBusinessUnit,useBusinessUnits,useCreateBusinessUnit,useUpdateBusinessUnit,type BusinessUnitInput,type BusinessUnitType } from '@/lib/business-units';

const initial:BusinessUnitInput={name:'',type:'DIVISION',parentUnitId:null};
export function BusinessUnitFormPage({mode}:{mode:'create'|'edit'}){
 const{id=''}=useParams();const navigate=useNavigate();const detail=useBusinessUnit(mode==='edit'?id:'');const parents=useBusinessUnits(1,100);const create=useCreateBusinessUnit();const update=useUpdateBusinessUnit(id);const mutation=mode==='create'?create:update;const[form,setForm]=useState(initial);const[fieldErrors,setFieldErrors]=useState<Record<string,string[]>>({});
 useEffect(()=>{if(mode==='edit'&&detail.data)setForm({name:detail.data.name,type:detail.data.type,parentUnitId:detail.data.parentUnitId});},[mode,detail.data]);
 if(mode==='edit'&&detail.isLoading)return <div aria-label="Loading business unit" className="h-64 animate-pulse rounded-xl bg-muted"/>;
 if(mode==='edit'&&detail.isError)return <p role="alert">Business unit could not be loaded.</p>;
 const message=(name:string)=>fieldErrors[name]?.[0];
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setFieldErrors({});try{const record=mode==='create'?await create.mutateAsync(form):await update.mutateAsync({...form,version:detail.data!.version});navigate(`/business-units/${record.id}`);}catch(error){if(error instanceof ApiError&&error.fields)setFieldErrors(error.fields);}};
 const conflict=mutation.error instanceof ApiError&&mutation.error.code==='CONCURRENCY_CONFLICT';
 return <div className="mx-auto max-w-2xl"><h1 className="text-2xl font-semibold tracking-tight">{mode==='create'?'Create business unit':'Edit business unit'}</h1><p className="mt-2 text-sm text-muted-foreground">Define where this unit sits in the active organization.</p>{mutation.isError&&<p role="alert" className="mt-6 rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive">{conflict?'This business unit changed after you loaded it. Reload the page and reapply your changes.':mutation.error.message}</p>}<form onSubmit={submit} className="mt-8 space-y-6"><label className="block text-sm font-medium" htmlFor="business-unit-name">Unit name<input id="business-unit-name" className="field mt-2 aria-invalid:border-destructive" required value={form.name} aria-invalid={Boolean(message('name'))} aria-describedby={message('name')?'business-unit-name-error':undefined} onChange={e=>setForm(current=>({...current,name:e.target.value}))}/>{message('name')&&<span id="business-unit-name-error" className="mt-1 block text-xs text-destructive">{message('name')}</span>}</label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium" htmlFor="business-unit-type">Type<select id="business-unit-type" className="field mt-2" value={form.type} onChange={e=>setForm(current=>({...current,type:e.target.value as BusinessUnitType}))}><option value="DIVISION">Division</option><option value="SUBSIDIARY">Subsidiary</option><option value="FUNCTION">Function</option><option value="OTHER">Other</option></select></label><label className="block text-sm font-medium" htmlFor="business-unit-parent">Parent unit<select id="business-unit-parent" className="field mt-2 aria-invalid:border-destructive" value={form.parentUnitId??''} disabled={parents.isLoading||parents.isError} aria-invalid={Boolean(message('parentUnitId'))} aria-describedby={message('parentUnitId')?'business-unit-parent-error':undefined} onChange={e=>setForm(current=>({...current,parentUnitId:e.target.value||null}))}><option value="">No parent</option>{parents.data?.data.filter(item=>item.id!==id).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select>{parents.isLoading&&<span className="mt-1 block text-xs text-muted-foreground">Loading parent units…</span>}{parents.isError&&<span role="alert" className="mt-1 block text-xs text-destructive">Parent units could not be loaded. Retry before saving.</span>}{message('parentUnitId')&&<span id="business-unit-parent-error" className="mt-1 block text-xs text-destructive">{message('parentUnitId')}</span>}</label></div><div className="flex gap-3"><Button disabled={mutation.isPending||parents.isError}>{mutation.isPending?(mode==='create'?'Creating…':'Saving…'):(mode==='create'?'Create business unit':'Save changes')}</Button><Button asChild variant="ghost"><Link to={mode==='create'?'/business-units':`/business-units/${id}`}>Cancel</Link></Button></div></form></div>;
}
