import { useEffect, useState } from 'react';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { Building2 } from 'lucide-react';
import { PublicAuthLayout } from '@/components/auth/PublicAuthLayout';
import { Button } from '@/components/ui/button';
import { apiFetch } from '@/lib/api';
import { useAuth } from '@/lib/auth';
type Preview = { email: string; organizationName: string; accountExists: boolean }; type Values = { displayName: string; password: string };
export function InvitationAcceptancePage() {
  const [params] = useSearchParams(); const token = params.get('token') ?? ''; const auth = useAuth(); const navigate = useNavigate(); const [preview, setPreview] = useState<Preview | null>(null); const [error, setError] = useState(''); const [done, setDone] = useState(false); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>();
  useEffect(() => { if (token) void apiFetch<Preview>('/invitations/preview', { method: 'POST', body: JSON.stringify({ token }) }).then(setPreview).catch(caught => setError(caught instanceof Error ? caught.message : 'This invitation is invalid or expired.')); else setError('This invitation link is incomplete.'); }, [token]);
  if (done) return <Navigate to="/dashboard" replace />;
  const finish = async (work: () => Promise<unknown>) => { setError(''); try { await work(); sessionStorage.removeItem('pendingInvitationMfa'); setDone(true); } catch (caught) { setError(caught instanceof Error ? caught.message : 'The invitation could not be accepted.'); } };
  const submit = handleSubmit(values => finish(async () => { if (!preview) return; if (preview.accountExists) { const result = await auth.acceptInvitationWithPassword({ email: preview.email, password: values.password, token }); if (result === 'mfa') navigate('/mfa-challenge'); } else await auth.acceptNewInvitation({ token, ...values }); }));
  return <PublicAuthLayout eyebrow="Invitation" title={preview ? `Join ${preview.organizationName}` : 'Checking your invitation'} description={preview ? `This invitation is for ${preview.email}. Access is limited to the organization and roles selected by the inviter.` : 'Please wait while we validate the link.'}>
    {preview && <><div className="mb-6 flex items-center gap-3 rounded-lg bg-primary/10 p-4 text-sm"><Building2 className="h-5 w-5 text-primary" /><span>{auth.user ? 'Confirm to add this organization to your signed-in account.' : preview.accountExists ? 'Sign in to add this organization to your existing account.' : 'Create your identity to join this organization.'}</span></div>{auth.user ? <div className="space-y-4">{error && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button className="h-11 w-full" onClick={() => void finish(() => auth.authenticatedFetch('/invitations/accept', { method: 'POST', body: JSON.stringify({ token }) }))}>Accept invitation</Button></div> : <form className="space-y-5" onSubmit={submit}>{!preview.accountExists && <><label className="block text-sm font-medium" htmlFor="invitee-name">Your name<input id="invitee-name" className="mt-2 h-11 w-full rounded-md border bg-background px-3" aria-invalid={!!errors.displayName} aria-describedby={errors.displayName ? 'invitee-name-error' : undefined} {...register('displayName', { required: 'Enter your name.' })} /></label>{errors.displayName && <p id="invitee-name-error" className="text-xs text-destructive">{errors.displayName.message}</p>}</>}<label className="block text-sm font-medium" htmlFor="invitee-password">Password<input id="invitee-password" type="password" autoComplete={preview.accountExists ? 'current-password' : 'new-password'} className="mt-2 h-11 w-full rounded-md border bg-background px-3" aria-invalid={!!errors.password} aria-describedby={errors.password ? 'invitee-password-error' : undefined} {...register('password', { required: 'Enter your password.', minLength: preview.accountExists ? undefined : { value: 12, message: 'Use at least 12 characters.' } })} /></label>{errors.password && <p id="invitee-password-error" className="text-xs text-destructive">{errors.password.message}</p>}{error && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button className="h-11 w-full" disabled={isSubmitting}>{isSubmitting ? 'Joining…' : 'Accept invitation'}</Button></form>}</>}
    {!preview && error && <div role="alert" className="rounded-lg bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}<p className="mt-6 text-center text-sm"><Link className="text-primary hover:underline" to="/login">Back to sign in</Link></p>
  </PublicAuthLayout>;
}
