import { useEffect, useRef, useState } from 'react';
import { useForm } from 'react-hook-form';
import { CheckCircle2, UserPlus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ApiError } from '@/lib/api';
import { useAuth } from '@/lib/auth';
type Role = { id: string; name: string; description: string | null };
type Values = { email: string; roleIds: string[] };
export function InviteUserPage() {
  const { user, authenticatedFetch } = useAuth(); const organizations = user?.memberships?.filter(item => item.status === 'ACTIVE') ?? [];
  const [organizationId, setOrganizationId] = useState(organizations[0]?.organizationId ?? ''); const [roles, setRoles] = useState<Role[]>([]); const [rolesLoading, setRolesLoading] = useState(false); const [loadError, setLoadError] = useState(''); const [success, setSuccess] = useState(''); const requestSequence = useRef(0);
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<Values>({ defaultValues: { roleIds: [] } });
  useEffect(() => { if (!organizationId) return; const sequence = ++requestSequence.current; setRoles([]); reset({ email: '', roleIds: [] }); setLoadError(''); setRolesLoading(true); void authenticatedFetch<Role[]>(`/invitations/roles?organizationId=${encodeURIComponent(organizationId)}`).then(nextRoles => { if (requestSequence.current === sequence) setRoles(nextRoles); }).catch(error => { if (requestSequence.current === sequence) setLoadError(error instanceof Error ? error.message : 'Roles could not be loaded.'); }).finally(() => { if (requestSequence.current === sequence) setRolesLoading(false); }); }, [authenticatedFetch, organizationId, reset]);
  const submit = handleSubmit(async values => { setLoadError(''); setSuccess(''); try { await authenticatedFetch('/invitations', { method: 'POST', body: JSON.stringify({ organizationId, email: values.email, roleIds: values.roleIds ?? [] }) }); setSuccess(`Invitation sent to ${values.email}.`); reset(); } catch (error) { setLoadError(error instanceof ApiError ? error.message : 'Invitation could not be sent.'); } });
  return <div className="mx-auto max-w-2xl space-y-7">
    <header><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><UserPlus className="h-5 w-5" /></span><h1 className="text-2xl font-semibold tracking-tight">Invite a user</h1></div><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Grant access to one organization. Only roles within your own assignment authority are shown.</p></header>
    <form className="space-y-6 rounded-xl border bg-card p-5 shadow-sm sm:p-7" onSubmit={submit}>
      <label className="block text-sm font-medium" htmlFor="invite-organization">Organization<select id="invite-organization" className="mt-2 h-11 w-full rounded-md border bg-background px-3" value={organizationId} onChange={event => setOrganizationId(event.target.value)}>{organizations.map(org => <option key={org.organizationId} value={org.organizationId}>{org.organizationName}</option>)}</select></label>
      <label className="block text-sm font-medium" htmlFor="invite-email">Work email<input id="invite-email" type="email" autoComplete="email" className="mt-2 h-11 w-full rounded-md border bg-background px-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" aria-invalid={!!errors.email} aria-describedby={errors.email ? 'invite-email-error' : undefined} {...register('email', { required: 'Enter the invitee’s email.' })} /></label>{errors.email && <p id="invite-email-error" className="-mt-4 text-xs text-destructive">{errors.email.message}</p>}
      <fieldset aria-describedby={errors.roleIds ? 'invite-roles-error' : undefined}><legend className="text-sm font-medium">Roles</legend><p className="mt-1 text-xs text-muted-foreground">Choose at least one role. Permissions are combined when multiple roles are selected.</p><div className="mt-3 divide-y rounded-lg border">{roles.map(role => <label className="flex cursor-pointer items-start gap-3 p-4 hover:bg-muted/50" key={role.id}><input className="mt-1 h-4 w-4 accent-primary" type="checkbox" value={role.id} {...register('roleIds', { required: 'Select at least one role.' })} /><span><strong className="block text-sm font-medium">{role.name}</strong>{role.description && <span className="mt-1 block text-xs text-muted-foreground">{role.description}</span>}</span></label>)}{!roles.length && !loadError && <p className="p-4 text-sm text-muted-foreground">{rolesLoading ? 'Loading assignable roles…' : 'No assignable roles are available.'}</p>}</div></fieldset>{errors.roleIds && <p id="invite-roles-error" className="-mt-4 text-xs text-destructive">{errors.roleIds.message}</p>}
      {loadError && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{loadError}</p>}{success && <p role="status" className="flex items-center gap-2 rounded-md bg-green-500/10 p-3 text-sm text-green-800 dark:text-green-300"><CheckCircle2 className="h-4 w-4" />{success}</p>}
      <div className="flex justify-end"><Button className="h-11 px-5" disabled={isSubmitting || rolesLoading || !roles.length}>{isSubmitting ? 'Sending…' : 'Send invitation'}</Button></div>
    </form>
  </div>;
}
