import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Copy, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/lib/auth';
type Setup = { secret: string; otpauthUri: string }; type Confirmation = { enabled: true; recoveryCodes: string[] };
export function MfaSetupPage() {
  const { authenticatedFetch } = useAuth(); const [setup, setSetup] = useState<Setup | null>(null); const [codes, setCodes] = useState<string[]>([]); const [error, setError] = useState(''); const [starting, setStarting] = useState(false); const [copyStatus, setCopyStatus] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<{ code: string }>();
  const start = async () => { setStarting(true); setError(''); try { setSetup(await authenticatedFetch<Setup>('/auth/mfa/enroll', { method: 'POST' })); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Setup could not be started.'); } finally { setStarting(false); } };
  const copy = async () => { try { await navigator.clipboard.writeText(codes.join('\n')); setCopyStatus('Codes copied.'); } catch { setCopyStatus('Copy was blocked. Select and save the codes manually.'); } };
  return <div className="mx-auto max-w-2xl space-y-6"><header className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><ShieldCheck className="h-5 w-5" /></span><div><h1 className="text-2xl font-semibold">Multi-factor authentication</h1><p className="text-sm text-muted-foreground">Protect your account with a time-based authenticator.</p></div></header><section className="rounded-xl border bg-card p-6 shadow-sm">
    {!setup && !codes.length && <div className="space-y-3"><Button disabled={starting} onClick={() => void start()}>{starting ? 'Starting…' : 'Start setup'}</Button>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div>}
    {setup && !codes.length && <form className="space-y-5" onSubmit={handleSubmit(async ({ code }) => { setError(''); try { const result = await authenticatedFetch<Confirmation>('/auth/mfa/confirm', { method: 'POST', body: JSON.stringify({ code }) }); setCodes(result.recoveryCodes); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Code could not be verified.'); } })}><p className="text-sm">Add this secret to your authenticator app, then enter its current code.</p><code className="block break-all rounded-md bg-muted p-3 text-sm">{setup.secret}</code><label className="block text-sm font-medium" htmlFor="setup-mfa-code">Six-digit code<input id="setup-mfa-code" inputMode="numeric" className="mt-2 h-11 w-full rounded-md border bg-background px-3" aria-invalid={!!errors.code} aria-describedby={errors.code ? 'setup-mfa-code-error' : undefined} {...register('code', { required: 'Enter the current six-digit code.' })} /></label>{errors.code && <p id="setup-mfa-code-error" className="text-sm text-destructive">{errors.code.message}</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={isSubmitting}>{isSubmitting ? 'Confirming…' : 'Confirm enrollment'}</Button></form>}
    {codes.length > 0 && <div><h2 className="text-lg font-semibold">Save your recovery codes</h2><p className="mt-1 text-sm text-muted-foreground">Each code works once. Store them somewhere safe before leaving this page.</p><div className="mt-4 grid grid-cols-1 gap-2 rounded-lg bg-muted p-4 font-mono text-sm sm:grid-cols-2">{codes.map(code => <span key={code}>{code}</span>)}</div><Button className="mt-4" variant="outline" onClick={() => void copy()}><Copy className="mr-2 h-4 w-4" />Copy codes</Button><p aria-live="polite" className="mt-2 text-sm text-muted-foreground">{copyStatus}</p></div>}
  </section></div>;
}
