import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { PublicAuthLayout } from '@/components/auth/PublicAuthLayout';
import { Button } from '@/components/ui/button';
import { ApiError, apiFetch } from '@/lib/api';
type Values = { password: string; confirmation: string };
export function NewPasswordPage() {
  const [params] = useSearchParams(); const token = params.get('token') ?? ''; const [done, setDone] = useState(false); const [tokenError, setTokenError] = useState(token ? '' : 'This reset link is missing or invalid.');
  const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<Values>();
  const submit = handleSubmit(async value => { setTokenError(''); try { await apiFetch('/auth/password-reset/complete', { method: 'POST', body: JSON.stringify({ token, password: value.password }) }); setDone(true); } catch (error) { setTokenError(error instanceof ApiError ? error.message : 'Password reset failed. Please request a new link.'); } });
  return <PublicAuthLayout eyebrow="Account recovery" title={done ? 'Password updated' : 'Choose a new password'} description={done ? 'Previous sessions have been signed out to protect your account.' : 'Use at least 12 characters. A memorable passphrase works well.'}>
    {done ? <Link className="inline-flex h-11 w-full items-center justify-center rounded-md bg-primary text-sm font-medium text-primary-foreground" to="/login">Sign in with new password</Link> : <form className="space-y-5" onSubmit={submit}><label className="block text-sm font-medium" htmlFor="new-password">New password<input id="new-password" type="password" autoComplete="new-password" className="mt-2 h-11 w-full rounded-md border bg-background px-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" aria-invalid={!!errors.password} aria-describedby={errors.password ? 'new-password-error' : undefined} {...register('password', { required: 'Enter a new password.', minLength: { value: 12, message: 'Use at least 12 characters.' } })} /></label>{errors.password && <p id="new-password-error" className="text-xs text-destructive">{errors.password.message}</p>}<label className="block text-sm font-medium" htmlFor="confirm-password">Confirm password<input id="confirm-password" type="password" autoComplete="new-password" className="mt-2 h-11 w-full rounded-md border bg-background px-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" aria-invalid={!!errors.confirmation} aria-describedby={errors.confirmation ? 'confirm-password-error' : undefined} {...register('confirmation', { required: 'Confirm your password.', validate: value => value === watch('password') || 'Passwords do not match.' })} /></label>{errors.confirmation && <p id="confirm-password-error" className="text-xs text-destructive">{errors.confirmation.message}</p>}{tokenError && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{tokenError}</p>}<Button className="h-11 w-full" disabled={isSubmitting || !token}>{isSubmitting ? 'Updating…' : 'Update password'}</Button><p className="text-center text-sm"><Link className="text-primary hover:underline" to="/forgot-password">Request a new link</Link></p></form>}
  </PublicAuthLayout>;
}
