import { useEffect, useState } from 'react';
import { Monitor, Smartphone } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/lib/auth';
type Session = { id: string; ipAddress: string | null; userAgent: string | null; createdAt: string; lastSeenAt: string; expiresAt: string };
export function SessionsPage() {
  const { authenticatedFetch } = useAuth(); const [sessions, setSessions] = useState<Session[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [revoking, setRevoking] = useState<string | null>(null);
  const load = () => authenticatedFetch<Session[]>('/auth/sessions').then(setSessions).catch(() => setError('Sessions could not be loaded. Try again.')).finally(() => setLoading(false));
  useEffect(() => { void load(); }, []);
  const revoke = async (id: string) => { setError(''); setRevoking(id); try { await authenticatedFetch(`/auth/sessions/${id}`, { method: 'DELETE' }); setSessions(items => items.filter(item => item.id !== id)); } catch { setError('That session could not be revoked. Check your connection and try again.'); } finally { setRevoking(null); } };
  return <div className="mx-auto max-w-3xl"><h1 className="text-2xl font-semibold tracking-tight">Active sessions</h1><p className="mt-2 text-sm text-muted-foreground">Review browsers with access to your account and revoke anything unfamiliar.</p>{error && <p role="alert" className="mt-6 rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}{loading ? <div className="mt-8 h-24 animate-pulse rounded-xl bg-muted" /> : <div className="mt-8 divide-y rounded-xl border bg-card">{sessions.length === 0 ? <p className="p-6 text-sm text-muted-foreground">No active sessions remain.</p> : sessions.map(session => { const mobile = /mobile|android|iphone/i.test(session.userAgent ?? ''); const busy = revoking === session.id; return <div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start" key={session.id}><div className="flex min-w-0 flex-1 items-start gap-4">{mobile ? <Smartphone className="mt-1 h-5 w-5 shrink-0 text-muted-foreground" /> : <Monitor className="mt-1 h-5 w-5 shrink-0 text-muted-foreground" />}<div className="min-w-0"><p className="break-words text-sm font-medium">{session.userAgent || 'Unknown browser'}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{session.ipAddress || 'Unknown address'} · Last active {new Date(session.lastSeenAt).toLocaleString()}</p></div></div><Button className="w-full sm:w-auto" variant="outline" size="sm" disabled={busy || revoking !== null} onClick={() => void revoke(session.id)}>{busy ? 'Revoking…' : 'Revoke'}</Button></div>; })}</div>}</div>;
}
