import { useEffect, useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/lib/auth';
type Workflow={id:string;version:number;name:string;trigger:string;conditions:unknown[];actors:unknown[];deadlineSeconds:number|null;escalation:Record<string,unknown>|null;outcomes:Record<string,unknown>;active:boolean};
const pretty=(value:unknown)=>JSON.stringify(value,null,2);
export function WorkflowSettingsPage(){
 const{authenticatedFetch}=useAuth();const[items,setItems]=useState<Workflow[]>([]);const[selected,setSelected]=useState<Workflow|null>(null);const[name,setName]=useState('');const[trigger,setTrigger]=useState('RECORD_SUBMITTED');const[deadline,setDeadline]=useState('86400');const[conditions,setConditions]=useState('[]');const[actors,setActors]=useState('[\n  { "type": "ASSIGNEE" }\n]');const[outcomes,setOutcomes]=useState('{\n  "approve": "APPROVED",\n  "reject": "REJECTED"\n}');const[escalation,setEscalation]=useState('{}');const[active,setActive]=useState(true);const[error,setError]=useState('');const[saving,setSaving]=useState(false);
 const load=()=>authenticatedFetch<Workflow[]>('/api/v1/workflows').then(setItems).catch(()=>setError('Workflow definitions could not be loaded.'));
 useEffect(()=>{void load();},[]);
 const choose=(item:Workflow)=>{setSelected(item);setName(item.name);setTrigger(item.trigger);setDeadline(String(item.deadlineSeconds??86400));setConditions(pretty(item.conditions));setActors(pretty(item.actors));setOutcomes(pretty(item.outcomes));setEscalation(pretty(item.escalation??{}));setActive(item.active!==false);};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const payload={id:selected?.id,name,trigger,conditions:JSON.parse(conditions),actors:JSON.parse(actors),deadlineSeconds:Number(deadline),outcomes:JSON.parse(outcomes),escalation:JSON.parse(escalation),active};if(!Array.isArray(payload.conditions)||!Array.isArray(payload.actors))throw new Error();await authenticatedFetch('/api/v1/workflows',{method:'POST',body:JSON.stringify(payload)});setSelected(null);setName('');await load();}catch{setError('The workflow could not be saved. Conditions and actors must be JSON arrays; outcomes and escalation must be JSON objects.');}finally{setSaving(false);}};
 return <div className="space-y-8"><div><h1 className="text-2xl font-semibold tracking-tight">Workflow settings</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Publish immutable approval-rule versions. Existing reviews retain the version they started with.</p></div>{error&&<p role="alert" className="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p>}<div className="grid gap-8 lg:grid-cols-[minmax(16rem,.7fr)_minmax(30rem,1.3fr)]"><section aria-label="Workflow definitions" className="divide-y border-y">{items.length===0?<p className="py-8 text-sm text-muted-foreground">No workflows configured.</p>:items.map(item=><button type="button" onClick={()=>choose(item)} key={item.id} className="flex w-full items-center justify-between gap-5 py-4 text-left hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span><span className="block font-medium">{item.name}</span><span className="mt-1 block text-xs text-muted-foreground">{item.trigger} · {item.active?'Active':'Inactive'}</span></span><span className="tabular-nums text-xs text-muted-foreground">v{item.version}</span></button>)}</section><form onSubmit={save} className="space-y-5 rounded-xl border bg-card p-5"><h2 className="text-base font-semibold">{selected?'Publish new version':'New workflow'}</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><input required minLength={2} value={name} onChange={e=>setName(e.target.value)} className="field"/></Field><Field label="Trigger"><input required value={trigger} onChange={e=>setTrigger(e.target.value)} className="field"/></Field></div><div className="grid gap-4 sm:grid-cols-2"><JsonField label="Conditions" value={conditions} setValue={setConditions}/><JsonField label="Actors" value={actors} setValue={setActors}/><JsonField label="Outcomes" value={outcomes} setValue={setOutcomes}/><JsonField label="Escalation" value={escalation} setValue={setEscalation}/></div><div className="flex flex-wrap items-end gap-5"><Field label="Deadline in seconds"><input required type="number" min="1" max="31536000" value={deadline} onChange={e=>setDeadline(e.target.value)} className="field w-56 tabular-nums"/></Field><label className="flex h-10 items-center gap-2 text-sm font-medium"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} className="h-4 w-4"/>Active for future reviews</label></div><div className="flex gap-2"><Button disabled={saving}>{saving?'Saving…':'Save workflow'}</Button>{selected&&<Button type="button" variant="ghost" onClick={()=>{setSelected(null);setName('');}}>Cancel</Button>}</div></form></div></div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-sm font-medium">{label}<span className="mt-2 block">{children}</span></label>}
function JsonField({label,value,setValue}:{label:string;value:string;setValue:(value:string)=>void}){return <label className="block text-sm font-medium">{label}<textarea aria-label={label} spellCheck={false} rows={5} value={value} onChange={e=>setValue(e.target.value)} className="mt-2 w-full resize-y rounded-md border bg-background p-3 font-mono text-xs leading-5"/></label>}
