import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useAuth } from './auth';
export type Organization={id:string;name:string;industry:string|null;registrationNumber:string|null;country:string|null;timezone:string;employeeCount:number|null;website:string|null;contacts:Array<{name:string;email?:string;phone?:string}>;version:number;createdAt:string;updatedAt:string};
export type OrganizationInput={name:string;industry?:string;registrationNumber?:string;country?:string;timezone:string;employeeCount?:number;website?:string;contacts?:Organization['contacts']};
type Page={data:Organization[];total:number;page:number;limit:number};
export const organizationKeys={all:['organizations'] as const,list:(page:number)=>['organizations','list',page] as const,detail:(id:string)=>['organizations','detail',id] as const};
export function useOrganizations(page:number,limit=20){const{authenticatedFetch}=useAuth();return useQuery({queryKey:organizationKeys.list(page),queryFn:()=>authenticatedFetch<Page>(`/api/v1/organizations?page=${page}&limit=${limit}`)});}
export function useOrganization(id:string){const{authenticatedFetch}=useAuth();return useQuery({queryKey:organizationKeys.detail(id),queryFn:()=>authenticatedFetch<Organization>(`/api/v1/organizations/${id}`),enabled:Boolean(id)});}
export function useCreateOrganization(){const{authenticatedFetch}=useAuth();const client=useQueryClient();return useMutation({mutationFn:(input:OrganizationInput)=>authenticatedFetch<Organization>('/api/v1/organizations',{method:'POST',body:JSON.stringify(input)}),onSuccess:async(record)=>{await client.invalidateQueries({queryKey:organizationKeys.all});client.setQueryData(organizationKeys.detail(record.id),record);}});}
export function useUpdateOrganization(id:string){const{authenticatedFetch}=useAuth();const client=useQueryClient();return useMutation({mutationFn:(input:Partial<OrganizationInput>&{version:number})=>authenticatedFetch<Organization>(`/api/v1/organizations/${id}`,{method:'PATCH',body:JSON.stringify(input)}),onSuccess:async(record)=>{client.setQueryData(organizationKeys.detail(id),record);await client.invalidateQueries({queryKey:organizationKeys.all});}});}
