import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { useEditions, useRequirements, useWorkflowAction, type Edition } from '@/lib/control-workflows';

const Feedback = ({ pending, error, success }: { pending: boolean; error?: string; success?: string }) => error ? <p role="alert" className="text-sm text-destructive">{error}</p> : !pending && success ? <p role="status" className="text-sm text-primary">{success}</p> : null;

export function FrameworkVersionsPanel({ frameworkId, editable }: { frameworkId: string; editable: boolean }) {
  const query = useEditions(frameworkId), editions = Array.isArray(query.data) ? query.data : [];
  const [selected, setSelected] = useState(''), [showNew, setShowNew] = useState(false);
  const [newEdition, setNewEdition] = useState({ versionIdentifier: '', effectiveDate: new Date().toISOString().slice(0, 10) });
  const [draft, setDraft] = useState({ domainReference: '', domainName: '', reference: '', description: '', weight: 1 });
  useEffect(() => { if (!selected && editions[0]) setSelected(editions[0].id); }, [editions, selected]);
  const requirementsQuery = useRequirements(selected), requirements = Array.isArray(requirementsQuery.data) ? requirementsQuery.data : [];
  const create = useWorkflowAction<typeof newEdition, Edition>(`/api/v1/frameworks/${frameworkId}/versions`);
  const save = useWorkflowAction<typeof draft, unknown>(`/api/v1/framework-versions/${selected}/requirements`);
  const publish = useWorkflowAction<{ expectedRequirementCount: number }, unknown>(`/api/v1/framework-versions/${selected}/publish`);
  const edition = editions.find(item => item.id === selected);
  return <section className="border-t py-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-semibold">Framework editions</h2><p className="mt-1 text-sm text-muted-foreground">Requirements remain pinned to the selected immutable edition.</p></div>{editable && <Button variant="outline" onClick={() => setShowNew(value => !value)}>{showNew ? 'Cancel' : 'New draft edition'}</Button>}</div>
    {showNew && <form className="mt-5 grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_12rem_auto] sm:items-end" onSubmit={async event => { event.preventDefault(); const created = await create.mutateAsync(newEdition); setSelected(created.id); setShowNew(false); }}><label htmlFor="edition-identifier" className="text-sm font-medium">Edition identifier<input id="edition-identifier" required className="field mt-2" value={newEdition.versionIdentifier} onChange={event => setNewEdition(value => ({ ...value, versionIdentifier: event.target.value }))}/></label><label htmlFor="edition-effective" className="text-sm font-medium">Effective date<input id="edition-effective" required type="date" className="field mt-2" value={newEdition.effectiveDate} onChange={event => setNewEdition(value => ({ ...value, effectiveDate: event.target.value }))}/></label><Button disabled={create.isPending}>{create.isPending ? 'Creating…' : 'Create draft'}</Button><div className="sm:col-span-3"><Feedback pending={create.isPending} error={create.isError ? create.error.message : undefined}/></div></form>}
    {create.isSuccess && !showNew && <p role="status" className="mt-4 text-sm text-primary">Draft edition created.</p>}
    <label htmlFor="framework-edition" className="mt-5 block max-w-sm text-sm font-medium">Edition<select id="framework-edition" className="field mt-2" value={selected} onChange={event => setSelected(event.target.value)}><option value="">Select an edition</option>{editions.map(item => <option key={item.id} value={item.id}>{item.versionIdentifier} · {item.status} · {item.requirementCount} requirements</option>)}</select></label>
    {requirementsQuery.isLoading && <div className="mt-6 h-24 animate-pulse rounded-lg bg-muted"/>}
    {requirements.length ? <div className="mt-6 divide-y border-y">{requirements.map(item => <div key={item.id} className="grid gap-2 py-4 sm:grid-cols-[9rem_1fr_5rem]"><strong>{item.reference}</strong><span>{item.description}</span><span className="text-right tabular-nums">{item.weight}</span></div>)}</div> : selected && !requirementsQuery.isLoading && <p className="mt-6 text-sm text-muted-foreground">This edition has no requirements. Check its provenance before importing permitted content.</p>}
    {editable && edition?.status === 'DRAFT' && <form className="mt-6 grid gap-3 rounded-xl border p-5" onSubmit={async event => { event.preventDefault(); publish.reset(); await save.mutateAsync(draft); setDraft({ domainReference: '', domainName: '', reference: '', description: '', weight: 1 }); }}><h3 className="font-semibold">Add requirement</h3><div className="grid gap-3 sm:grid-cols-2"><label htmlFor="domain-reference" className="text-sm">Domain reference<input id="domain-reference" required className="field mt-2" value={draft.domainReference} onChange={event => setDraft(value => ({ ...value, domainReference: event.target.value }))}/></label><label htmlFor="domain-name" className="text-sm">Domain name<input id="domain-name" required className="field mt-2" value={draft.domainName} onChange={event => setDraft(value => ({ ...value, domainName: event.target.value }))}/></label><label htmlFor="requirement-reference" className="text-sm">Requirement reference<input id="requirement-reference" required className="field mt-2" value={draft.reference} onChange={event => setDraft(value => ({ ...value, reference: event.target.value }))}/></label><label htmlFor="requirement-weight" className="text-sm">Weight<input id="requirement-weight" required type="number" min="0.0001" step="0.0001" className="field mt-2" value={draft.weight} onChange={event => setDraft(value => ({ ...value, weight: Number(event.target.value) }))}/></label></div><label htmlFor="requirement-description" className="text-sm">Requirement text<textarea id="requirement-description" required className="field mt-2 min-h-24 py-3" value={draft.description} onChange={event => setDraft(value => ({ ...value, description: event.target.value }))}/></label><div className="flex gap-2"><Button disabled={save.isPending}>{save.isPending ? 'Adding…' : 'Add requirement'}</Button><Button type="button" variant="outline" disabled={publish.isPending} onClick={() => { save.reset(); publish.mutate({ expectedRequirementCount: requirements.length }); }}>{publish.isPending ? 'Publishing…' : 'Publish edition'}</Button></div><Feedback pending={save.isPending || publish.isPending} error={save.isError ? save.error.message : publish.isError ? publish.error.message : undefined} success={publish.isSuccess ? 'Edition published.' : save.isSuccess ? 'Requirement added.' : undefined}/></form>}
  </section>;
}
